version: 1	

update_configs:	

- package_manager: javascript	
  directory: "/"	
  update_schedule: live
  default_assignees: 	
    - brentonhouse	
  default_labels:	
    - dependencies	
    - dependabot	
  allowed_updates:
    - match:
        dependency_type: direct
  version_requirement_updates: increase_versions
  ignored_updates:
    - match:
        dependency_name: should
  automerged_updates:
    - match:
        dependency_name: "@titanium/*"
        update_type: all
    - match:
        dependency_type: production
        update_type: semver:patch
    - match:
        dependency_type: development
        update_type: semver:minor
    - match:
        dependency_name: lodash*
        update_type: semver:minor
    - match:
        dependency_name: eslint*
        update_type: semver:minor